//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DdacAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string Amount { get; set; }
        public string type { get; set; }
        public string cardholder_name { get; set; }
        public string card_number { get; set; }
        public string expiration_date { get; set; }
        public string card_cvv { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
