//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DdacAssignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int Id { get; set; }
        public System.DateTime departure_time { get; set; }
        public System.DateTime arrival_time { get; set; }
        public string destination { get; set; }
        public int ShipId { get; set; }
    
        public virtual Ship Ship { get; set; }
    }
}
